//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Plugins/Input/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""All"",
            ""id"": ""18cffab8-9eae-476c-92cd-82961f0ec84b"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f9551447-dea1-4d00-bdfd-086380183015"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CoursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""6e0dc99b-855d-48f6-a512-6fbc25dd8206"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DoButton"",
                    ""type"": ""Button"",
                    ""id"": ""fc94b0ec-8c78-43ea-8385-f160801ba7cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelButton"",
                    ""type"": ""Button"",
                    ""id"": ""489b645d-58b6-498f-90e3-6c4d06d4dd89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""08804e7b-5bb7-4346-be2c-01ac6d5eb0d2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""db27bc85-67b0-412a-8a00-cd3ae2d540f4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""333d20e5-3dd4-4cf9-a9bf-fe357944d695"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a519addb-935e-42d7-a4af-cf54ca25284a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""189c8637-95fa-464f-935a-5d4d458153f5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a81b9445-e889-43bc-8cc0-e297f9608d16"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""408ec767-6756-4ff3-be6d-a4dcf7c74e8a"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c40ca53-72c8-49cd-a5cb-ba6eeb7c0574"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""529492e8-558f-4a34-86ff-f90e1f4cdccc"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f955c5a2-543d-4105-a82d-ec4c0060080e"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // All
        m_All = asset.FindActionMap("All", throwIfNotFound: true);
        m_All_Move = m_All.FindAction("Move", throwIfNotFound: true);
        m_All_CoursorPosition = m_All.FindAction("CoursorPosition", throwIfNotFound: true);
        m_All_DoButton = m_All.FindAction("DoButton", throwIfNotFound: true);
        m_All_CancelButton = m_All.FindAction("CancelButton", throwIfNotFound: true);
        m_All_Zoom = m_All.FindAction("Zoom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // All
    private readonly InputActionMap m_All;
    private IAllActions m_AllActionsCallbackInterface;
    private readonly InputAction m_All_Move;
    private readonly InputAction m_All_CoursorPosition;
    private readonly InputAction m_All_DoButton;
    private readonly InputAction m_All_CancelButton;
    private readonly InputAction m_All_Zoom;
    public struct AllActions
    {
        private @InputSystem m_Wrapper;
        public AllActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_All_Move;
        public InputAction @CoursorPosition => m_Wrapper.m_All_CoursorPosition;
        public InputAction @DoButton => m_Wrapper.m_All_DoButton;
        public InputAction @CancelButton => m_Wrapper.m_All_CancelButton;
        public InputAction @Zoom => m_Wrapper.m_All_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_All; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AllActions set) { return set.Get(); }
        public void SetCallbacks(IAllActions instance)
        {
            if (m_Wrapper.m_AllActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_AllActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_AllActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_AllActionsCallbackInterface.OnMove;
                @CoursorPosition.started -= m_Wrapper.m_AllActionsCallbackInterface.OnCoursorPosition;
                @CoursorPosition.performed -= m_Wrapper.m_AllActionsCallbackInterface.OnCoursorPosition;
                @CoursorPosition.canceled -= m_Wrapper.m_AllActionsCallbackInterface.OnCoursorPosition;
                @DoButton.started -= m_Wrapper.m_AllActionsCallbackInterface.OnDoButton;
                @DoButton.performed -= m_Wrapper.m_AllActionsCallbackInterface.OnDoButton;
                @DoButton.canceled -= m_Wrapper.m_AllActionsCallbackInterface.OnDoButton;
                @CancelButton.started -= m_Wrapper.m_AllActionsCallbackInterface.OnCancelButton;
                @CancelButton.performed -= m_Wrapper.m_AllActionsCallbackInterface.OnCancelButton;
                @CancelButton.canceled -= m_Wrapper.m_AllActionsCallbackInterface.OnCancelButton;
                @Zoom.started -= m_Wrapper.m_AllActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_AllActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_AllActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_AllActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @CoursorPosition.started += instance.OnCoursorPosition;
                @CoursorPosition.performed += instance.OnCoursorPosition;
                @CoursorPosition.canceled += instance.OnCoursorPosition;
                @DoButton.started += instance.OnDoButton;
                @DoButton.performed += instance.OnDoButton;
                @DoButton.canceled += instance.OnDoButton;
                @CancelButton.started += instance.OnCancelButton;
                @CancelButton.performed += instance.OnCancelButton;
                @CancelButton.canceled += instance.OnCancelButton;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public AllActions @All => new AllActions(this);
    public interface IAllActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCoursorPosition(InputAction.CallbackContext context);
        void OnDoButton(InputAction.CallbackContext context);
        void OnCancelButton(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
